### ISSUE TITLE
add aura config

### ISSUE THREAD

**Issue by 0xTadash1** [0xTadash1/dotfiles#3]
```toml
[aur]
shellcheck = true
delmakedeps = true
clean = true
warn_unknowns = true
```
